### ISSUE TITLE
Use db:schema:load instead of db:migrate in setup instructions as the later is prone to errors 

### ISSUE THREAD

**Issue by bubunyo** [devcongress/elections-api#19]

**Comment by edemkumodzi** [comment]
@bubunyo are you talking about the setup instructions?

**Comment by bubunyo** [comment]
yeah I am, I will change the title to reflect that.

**Comment by yawboakye** [comment]
Should be `db:structure:load` instead since I changed the schema format to SQL (to take advantage of PostgreSQL features not supported/enabled by ActiveRecord yet). See https://github.com/devcongress/elections-api/blob/master/config/application.rb#L29

**Comment by edemkumodzi** [comment]
@bubunyo please create a PR to make the change. Thanks.

**Comment by bubunyo** [comment]
sure. I will add an `.env.example` file so that it can be easily renamed to create the `.env` file
